[build]
  base    = "."
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[functions."scrape-rates"]
  schedule = "10 4 * * 0-4" # 10:10 AM Dhaka, Sun-Thu (UTC offset +6)
